### PR TITLE
Feature/texturewriter stb

### PR DESCRIPTION
**Pull request by WeirdRubberDuck**
- Update stb_image version
- Add a STB texture writer, that can save textures to disk (supported formats:  jpg, jpeg, png, bmp, tga.  HDR is left out for now, se comment)
- Add a test to the test suite, that already erxisted but not actually compiled

Used in OpenSpace PR: https://github.com/OpenSpace/OpenSpace/pull/2912

### CODE REVIEW

**Review by alexanderbock — COMMENTED** [review]
Hmm..  reliably getting:

```
86>stb_imaged.lib(stb_image.obj) : error LNK2005: stbi_load_from_memory already defined in assimp-vc143-mtd.lib(Assimp.obj)
86>stb_imaged.lib(stb_image.obj) : error LNK2005: stbi_load_from_callbacks already defined in assimp-vc143-mtd.lib(Assimp.obj)
86>stb_imaged.lib(stb_image.obj) : error LNK2005: stbi_load already defined in assimp-vc143-mtd.lib(Assimp.obj)
86>stb_imaged.lib(stb_image.obj) : error LNK2005: stbi_load_from_file already defined in assimp-vc143-mtd.lib(Assimp.obj)
86>stb_imaged.lib(stb_image.obj) : error LNK2005: stbi_load_16_from_memory already defined in assimp-vc143-mtd.lib(Assimp.obj)
```

When trying to compile

**Comment by WeirdRubberDuck** [comment]
> Hmm.. reliably getting:
> 
> ```
> 86>stb_imaged.lib(stb_image.obj) : error LNK2005: stbi_load_from_memory already defined in assimp-vc143-mtd.lib(Assimp.obj)
> 86>stb_imaged.lib(stb_image.obj) : error LNK2005: stbi_load_from_callbacks already defined in assimp-vc143-mtd.lib(Assimp.obj)
> 86>stb_imaged.lib(stb_image.obj) : error LNK2005: stbi_load already defined in assimp-vc143-mtd.lib(Assimp.obj)
> 86>stb_imaged.lib(stb_image.obj) : error LNK2005: stbi_load_from_file already defined in assimp-vc143-mtd.lib(Assimp.obj)
> 86>stb_imaged.lib(stb_image.obj) : error LNK2005: stbi_load_16_from_memory already defined in assimp-vc143-mtd.lib(Assimp.obj)
> ```
> 
> When trying to compile

That's odd, I can't reproduce those linking errors.  Did you try doing a completely clean build?

Unsure how to address it otherwise

**Comment by WeirdRubberDuck** [comment]
> Hmm.. reliably getting:
> 
> ```
> 86>stb_imaged.lib(stb_image.obj) : error LNK2005: stbi_load_from_memory already defined in assimp-vc143-mtd.lib(Assimp.obj)
> 86>stb_imaged.lib(stb_image.obj) : error LNK2005: stbi_load_from_callbacks already defined in assimp-vc143-mtd.lib(Assimp.obj)
> 86>stb_imaged.lib(stb_image.obj) : error LNK2005: stbi_load already defined in assimp-vc143-mtd.lib(Assimp.obj)
> 86>stb_imaged.lib(stb_image.obj) : error LNK2005: stbi_load_from_file already defined in assimp-vc143-mtd.lib(Assimp.obj)
> 86>stb_imaged.lib(stb_image.obj) : error LNK2005: stbi_load_16_from_memory already defined in assimp-vc143-mtd.lib(Assimp.obj)
> ```
> 
> When trying to compile

Eek, I got those now too when doing a completely clean build.  Will have to check out howto handle the duplicated dependency

**Comment by alexanderbock** [comment]
I think this might have been fixed with the recent AssImp update. Not getting the linker errors anymore

```
58>openspace-ui-launcher.vcxproj -> A:\openspace\OpenSpace\build\apps\OpenSpace\ext\launcher\RelWithDebInfo\openspace-ui-launcher.lib
58>Done building project "openspace-ui-launcher.vcxproj".
59>------ Build started: Project: OpenSpace, Configuration: RelWithDebInfo x64 ------
59>main.cpp
59>LINK : A:\openspace\OpenSpace\bin\RelWithDebInfo\OpenSpace.exe not found or not built by the last incremental link; performing full link
59>   Creating library A:/openspace/OpenSpace/build/apps/OpenSpace/RelWithDebInfo/OpenSpace.lib and object A:/openspace/OpenSpace/build/apps/OpenSpace/RelWithDebInfo/OpenSpace.exp
59>OpenSpace.vcxproj -> A:\openspace\OpenSpace\bin\RelWithDebInfo\OpenSpace.exe
59>													Deploying Qt libraries	Adding manifest...
========== Build: 59 succeeded, 0 failed, 15 up-to-date, 0 skipped ==========
========== Build completed at 16:33 and took 02:06.401 minutes ==========
```

**Pull request merged**
